import { useEffect, useState } from 'react';
import { Search, Plus, LayoutGrid, List, Film, Music2, Image as ImageIcon, FolderOpen, SlidersHorizontal, Type, ArrowUpRight, Play, Link2, Check, Trash2 } from 'lucide-react';
import { useEditor } from '../store';
import { shortTime } from '../model';
import { IconButton, Waveform } from './UI';
import TransitionPanel from './TransitionPanel';
import DrawingPanel from './DrawingPanel';
import BgmPanel from './BgmPanel';
import type { Asset, Clip } from '../types';

export const looks: { name: string; description: string; color: string; patch: Partial<Clip> }[] = [
  { name: 'オリジナル', description: 'ニュートラル', color: 'linear-gradient(140deg,#6b949a,#a1987e)', patch: { exposure: 0, contrast: 1, saturation: 1 } },
  { name: 'Cinematic', description: '深い陰影、映画のように', color: 'linear-gradient(140deg,#3f7177,#d9aa73)', patch: { exposure: -0.12, contrast: 1.2, saturation: 0.78 } },
  { name: 'Vivid', description: '鮮やかな色彩', color: 'linear-gradient(140deg,#3ec0ac,#f4c876)', patch: { exposure: 0.1, contrast: 1.12, saturation: 1.4 } },
  { name: 'Soft Film', description: 'やわらかなフィルム調', color: 'linear-gradient(140deg,#a2a9ad,#d2b6a2)', patch: { exposure: 0.18, contrast: 0.85, saturation: 0.78 } },
  { name: 'Noir', description: 'モノクローム', color: 'linear-gradient(140deg,#252930,#b2b6bb)', patch: { exposure: 0, contrast: 1.25, saturation: 0 } },
  { name: 'Muted', description: '静かな、落ち着いた色', color: 'linear-gradient(140deg,#667a7a,#a7a591)', patch: { exposure: -0.05, contrast: 0.95, saturation: 0.55 } }
];
export default function MediaLibrary({ onImport, onRelink, onRemove, importLabel }: { onImport: () => void; onRelink: (a: Asset) => void; onRemove: (id: string) => void; importLabel: string }) {
  const panel = useEditor(s => s.panel); const assets = useEditor(s => s.project.assets); const selected = useEditor(s => s.selected); const clips = useEditor(s => s.project.clips);
  const [creatingBlack,setCreatingBlack]=useState(false);
  const addBlack=async()=>{const state=useEditor.getState();if(creatingBlack||state.gestureActive||!window.luma)return;if(state.project.assets.length>=2000){state.notify('素材は最大2000個です。');return;}const initialProject=state.project;setCreatingBlack(true);try{const asset=await window.luma.blackVideo(state.project.width,state.project.height);const current=useEditor.getState();if(current.gestureActive){current.notify('素材のドラッグ中のため追加を中止しました。ドラッグ後にもう一度追加してください。');return;}if(current.project.assets.length>=2000){current.notify('素材は最大2000個です。');return;}if(current.project!==initialProject){current.notify('プロジェクトが変更されたため追加を中止しました。もう一度追加してください。');return;}current.importAssets([asset]);setSelectedAsset(asset.id);setSearch('');setFilter('all');current.notify('ブラックビデオを追加しました。タイムラインに配置して長さを調整できます。');}catch(error){useEditor.getState().notify((error as Error).message);}finally{setCreatingBlack(false);}};
  const [search, setSearch] = useState(''); const [list, setList] = useState(true); const [filter, setFilter] = useState('all');
  const [selectedAsset, setSelectedAsset] = useState<string | null>(null);
  useEffect(() => { if (!assets.some(a => a.id === selectedAsset)) setSelectedAsset(null); }, [assets, selectedAsset]);
  const preview = (id: string) => { useEditor.getState().stop(); useEditor.setState({ sourceId: id }); };
  const mediaKey = (e: React.KeyboardEvent) => {
    if (panel !== 'media' || !['Delete', 'Backspace'].includes(e.key) || e.nativeEvent.isComposing || e.repeat || e.ctrlKey || e.metaKey || e.altKey || e.shiftKey) return;
    if ((e.target as HTMLElement).closest('input, textarea, select, [contenteditable]')) return;
    e.preventDefault(); e.stopPropagation();
    if (selectedAsset && !useEditor.getState().gestureActive) onRemove(selectedAsset);
  };
  const selectedClip = clips.find(c => selected.includes(c.id));
  const filtered = assets.filter(a => a.name.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || a.kind === filter));
  return <section className="library-panel panel" onKeyDown={mediaKey}><div className="library-tabs" role="tablist" aria-label="素材パネル">{[{ id: 'media', label: 'メディア', icon: FolderOpen }, { id: 'effects', label: 'エフェクト', icon: SlidersHorizontal }, { id: 'titles', label: 'テキスト', icon: Type }, { id: 'draw', label: '図形', icon: ArrowUpRight }, { id: 'bgm', label: 'BGM', icon: Music2 }].map(tab => <button key={tab.id} role="tab" aria-selected={panel === tab.id} className={panel === tab.id ? 'selected' : ''} onClick={() => useEditor.getState().setPanel(tab.id as typeof panel)}><tab.icon size={14}/>{tab.label}</button>)}</div>
    {panel === 'media' ? <><div className="library-toolbar"><div className="library-breadcrumb">プロジェクト素材 <span>{assets.length}</span></div><IconButton label="素材を読み込む" onClick={onImport} disabled={!!importLabel}><Plus size={17}/></IconButton></div><div className="media-search"><Search size={14}/><input aria-label="素材を検索" placeholder="素材を検索..." value={search} onChange={e => setSearch(e.target.value)}/><kbd>⌕</kbd></div><div className="library-controls"><select aria-label="素材の種類" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">すべての素材</option><option value="video">動画</option><option value="audio">音声</option><option value="image">画像</option></select><div><IconButton label="グリッド表示" active={!list} onClick={() => setList(false)}><LayoutGrid size={14}/></IconButton><IconButton label="リスト表示" active={list} onClick={() => setList(true)}><List size={15}/></IconButton></div></div>
      <div className="media-selection-actions"><span>{assets.find(a => a.id === selectedAsset)?.name || 'クリックで素材を選択'}</span><IconButton label="選択素材をプロジェクトから削除 (Delete)" disabled={!selectedAsset} onClick={() => selectedAsset && onRemove(selectedAsset)}><Trash2 size={15}/></IconButton></div>
      <button className="selected-asset-add" disabled={!selectedAsset || !!assets.find(a => a.id === selectedAsset)?.offline} onClick={() => { if(selectedAsset) { const before = useEditor.getState().project; useEditor.getState().addAsset(selectedAsset); if (useEditor.getState().project !== before) useEditor.getState().notify('素材をタイムラインに追加しました。Spaceで再生できます。'); } }}><Plus size={14}/>選択素材をタイムラインに追加</button>
      <div className={`media-grid ${list ? 'list-view' : ''}`}>{filtered.map(a => <article className={`media-card ${selectedAsset === a.id ? 'chosen' : ''} ${a.offline ? 'offline' : ''}`} key={a.id} data-asset-id={a.id} tabIndex={0} aria-label={a.name} onClick={e => { setSelectedAsset(a.id); if (!(e.target as HTMLElement).closest('button')) e.currentTarget.focus(); }} draggable={!a.offline} onDragStart={e => { setSelectedAsset(a.id); e.dataTransfer.setData('application/x-luma-asset', a.id); e.dataTransfer.effectAllowed = 'copy'; }}>
        <div className="media-thumb-wrap"><button className={`media-thumb ${a.kind}`} aria-label={`${a.name} を選択`} aria-pressed={selectedAsset === a.id} onDoubleClick={() => preview(a.id)} onClick={() => setSelectedAsset(a.id)}>
          {a.kind === 'audio' ? <div className="audio-art"><Music2 size={23}/><Waveform values={a.waveform}/></div> : a.thumbnail ? <img src={a.thumbnail} alt="" draggable={false}/> : <div className="missing-thumb"><Link2 size={20}/>オフライン</div>}
          <span className="asset-type">{a.kind === 'audio' ? <Music2 size={11}/> : a.kind === 'image' ? <ImageIcon size={11}/> : <Film size={11}/>}</span><span className="asset-duration">{shortTime(a.duration)}</span>
        </button><button className="asset-preview-button" aria-label={`${a.name} をプレビュー`} title="プレビュー" onClick={() => preview(a.id)}><Play size={13}/></button></div><div className="media-card-info"><span title={a.name}>{a.name}</span><small>{a.kind === 'audio' ? 'WAV / AUDIO' : a.kind === 'image' ? `${a.width} × ${a.height}` : `${a.width} × ${a.height} · ${a.fps.toFixed(0)} fps`}</small>{a.proxy ? <span className="proxy-tag">PROXY</span> : null}</div>
        <button className="asset-add" title={a.offline ? '素材を再リンク' : 'タイムラインに追加'} aria-label={`${a.name} ${a.offline ? 'を再リンク' : 'を追加'}`} onClick={() => a.offline ? onRelink(a) : useEditor.getState().addAsset(a.id)}>{a.offline ? <Link2 size={14}/> : <Plus size={14}/>}</button>
      </article>)}{filtered.length === 0 ? <div className="empty-library"><FolderOpen size={26}/><p>{assets.length ? '条件に合う素材がありません' : 'まずは動画・写真・音声を読み込みましょう'}</p>{assets.length ? <button className="text-button" onClick={() => { setSearch(''); setFilter('all'); }}>検索条件をクリア</button> : <button className="text-button" onClick={onImport}>ファイルを選択</button>}</div> : null}</div>
      <button className="secondary-button" disabled={creatingBlack||!window.luma} onClick={addBlack}>{creatingBlack?'ブラックビデオを作成中…':'ブラックビデオを追加'}</button><button className="import-zone" onClick={onImport} disabled={!!importLabel}><span className="import-plus"><Plus size={16}/></span><strong>{importLabel || '素材を読み込む'}</strong><small>{importLabel ? '必要に応じてプレビュー用動画を作成中' : 'ドラッグ＆ドロップ、またはクリック'}</small></button><div className="library-foot"><span>{assets.length} アイテム</span><span>ローカルメディア <span className="green-dot"/></span></div></> : null}
    {panel === 'effects' ? <div className="effects-content"><TransitionPanel/><span className="eyebrow">MAKE IT YOURS</span><h3>映像に、表情を。</h3><p>クリップを選択してルックを適用。細かな調整はカラーパネルで。</p><div className="look-grid">{looks.map(look => <button key={look.name} className="look-card" onClick={() => { const s = useEditor.getState(); if (!selectedClip || ['audio','title'].includes(selectedClip.kind)) { s.notify('映像または画像クリップを選択してください'); return; } s.updateClip(selectedClip.id, look.patch); s.setInspectorTab('color'); }}><div style={{ background: look.color }}><div className="look-mountain"/><span>{look.name === 'オリジナル' ? <Check size={20}/> : <SlidersHorizontal size={18}/>}</span></div><strong>{look.name}</strong><small>{look.description}</small></button>)}</div><div className="effect-note"><strong>フェードイン / フェードアウト</strong><p>1つのクリップの始まりや終わりは、プロパティから調整できます。</p></div></div> : null}
    {panel === 'draw' ? <DrawingPanel/> : null}
    {panel === 'bgm' ? <BgmPanel/> : null}
    {panel === 'titles' ? <div className="effects-content"><span className="eyebrow">WORDS IN MOTION</span><h3>言葉も、映像の一部。</h3><p>テンプレートをクリックすると、再生ヘッドの位置に追加します。</p>{[{ style: 'hero', name: 'シネマタイトル', sample: 'YOUR STORY', description: '大きく、印象的な見出し' }, { style: 'minimal', name: 'ミニマル', sample: 'Less, but better.', description: 'シンプルで洗練されたテキスト' }, { style: 'subtitle', name: '字幕・キャプション', sample: 'あなたの言葉を、届けよう。', description: '読みやすい背景付きの字幕' }].map(t => <button className={`title-template ${t.style}`} key={t.style} onClick={() => useEditor.getState().addTitle(t.style as Clip['textStyle'])}><div>{t.sample}</div><footer><span><strong>{t.name}</strong><small>{t.description}</small></span><ArrowUpRight size={16}/></footer></button>)}</div> : null}
  </section>;
}
