import type { BasicVideoMask, BezierMaskPoint, BezierVideoMask, Clip, Crop } from '../src/types';
export const EMPTY_CROP: Readonly<Crop>;
export const DEFAULT_VIDEO_MASK: Readonly<BasicVideoMask>;
export const DEFAULT_BEZIER_MASK: Readonly<BezierVideoMask>;
export const MAX_BEZIER_MASK_POINTS: number;
export const MIN_BEZIER_COORD: number;
export const MAX_BEZIER_COORD: number;
export function effectiveCrop(clip: Partial<Clip> | undefined): Readonly<Crop>;
export function hasCrop(clip: Partial<Clip> | undefined): boolean;
export function hasVideoMask(clip: Partial<Clip> | undefined): boolean;
export function hasBezierMask(clip: Partial<Clip> | undefined): boolean;
export function clampCropEdge(crop: Readonly<Crop>, edge: keyof Crop, requested: number): number;
export function validateVideoMask(clip: Partial<Clip> | undefined): void;
export function resizeMaskAxis(opposite: number, desired: number, direction: -1 | 1): { center: number; size: number };
export function moveBezierAnchor(point: BezierMaskPoint, dx: number, dy: number): BezierMaskPoint;
export function moveBezierHandle(point: BezierMaskPoint, part: 'in' | 'out', dx: number, dy: number): BezierMaskPoint;
export function flattenBezierMask(mask: BezierVideoMask, subdivisions?: number): { x: number; y: number }[];
export function maskAlphaAt(clip: Partial<Clip> | undefined, u: number, v: number): number;
export function rasterizeBezierMask(clip: Partial<Clip> | undefined, width: number, height: number): Uint8Array;
export function ffmpegMaskExpression(clip: Partial<Clip> | undefined): string;
