const {_electron:electron}=require('playwright');const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
const {ffmpeg,run,probe}=require('../electron/media.cjs');const root=path.join(__dirname,'..');
async function verify(){
  const results=path.join(root,'test-results');await fs.mkdir(results,{recursive:true});await fs.mkdir(path.join(root,'.local'),{recursive:true});
  const profile=await fs.mkdtemp(path.join(root,'.local','rate-profile-')),env={...process.env,LUMA_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
  const videoFile=path.join(results,'速度変更の映像.mp4'),audioFile=path.join(results,'速度変更の音声.wav');
  await run(ffmpeg,['-y','-v','error','-f','lavfi','-i','color=blue:s=320x180:r=30:d=6','-vf',"drawbox=w=iw:h=ih:color=red:t=fill:enable='gte(t,3)'",'-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p',videoFile]);
  await run(ffmpeg,['-y','-v','error','-f','lavfi','-i','sine=frequency=660:duration=6',audioFile]);
  const executablePath=process.env.LUMA_VERIFY_EXE,app=await electron.launch({executablePath,args:executablePath?[]:[root],env,timeout:60000}),page=await app.firstWindow(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  try{
    await page.locator('.media-card').first().waitFor({timeout:60000});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1100,760));const file=path.join(results,'レート調整.luma');
    await app.evaluate(({dialog},data)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:data.inputs});dialog.showSaveDialog=async()=>({canceled:false,filePath:data.file});},{inputs:[videoFile,audioFile],file});
    await page.getByRole('button',{name:'読み込み',exact:true}).click();await page.getByRole('button',{name:'速度変更の音声.wav を追加',exact:true}).waitFor({timeout:60000});
    const save=async()=>{
      const before=(await fs.stat(file).catch(()=>null))?.mtimeMs;
      await page.keyboard.press('Control+s');
      // A clean snapshot has no dirty marker even while its save is pending.
      // Do not let the following Undo/edit race that native atomic write.
      const deadline=Date.now()+10000;
      while((await fs.stat(file).catch(()=>null))?.mtimeMs===before){assert.ok(Date.now()<deadline,'native rate-test project save completed');await new Promise(resolve=>setTimeout(resolve,25));}
      await page.waitForFunction(()=>!document.querySelector('.unsaved-dot'));
      return JSON.parse(await fs.readFile(file,'utf8'));
    };
    const demo=await save(),v=demo.clips.find(c=>c.kind==='video'),a=demo.clips.find(c=>c.kind==='audio');
    const p={...demo,name:'レート調整の検証',width:320,height:180,markers:[],clips:[{...v,assetId:demo.assets.find(a=>a.path===videoFile).id,name:'映像の区間',start:2,in:1,duration:4,volume:1,fadeIn:0,fadeOut:0},{...a,assetId:demo.assets.find(a=>a.path===audioFile).id,name:'音声の区間',start:2,in:1,duration:4,volume:1,fadeIn:0,fadeOut:0}]};
    await fs.writeFile(file,JSON.stringify(p));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.keyboard.press('Control+o');await page.getByRole('button',{name:p.name,exact:true}).waitFor();await page.keyboard.press('Home');
    if(await page.getByRole('button',{name:'スナップ (N)',exact:true}).getAttribute('aria-pressed')==='true')await page.getByRole('button',{name:'スナップ (N)',exact:true}).click();
    await page.getByRole('button',{name:'レート調整ツール（長さで再生速度を変更）',exact:true}).click();
    const divider=await page.getByRole('separator',{name:'タイムラインの高さを変更'}).boundingBox(),panel=await page.locator('.timeline-container').boundingBox();await page.mouse.move(divider.x+divider.width/2,divider.y+divider.height/2);await page.mouse.down();await page.mouse.move(divider.x+divider.width/2,divider.y+divider.height/2+panel.height-340);await page.mouse.up();
    const zoom=Number(await page.getByRole('slider',{name:'タイムラインのズーム',exact:true}).inputValue());
    await require('./check-clip-edges.cjs')(page,save,zoom,checks);
    const stretch=async(kind,edge,delta,cancel=false)=>{const handle=page.locator(`.timeline-clip.${kind} .trim-handle.${edge}`);await handle.scrollIntoViewIfNeeded();const h=await handle.boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+h.width/2+delta*zoom,h.y+h.height/2,{steps:6});if(cancel)await page.keyboard.press('Escape');await page.mouse.up();};
    await stretch('video','right',-2);let changed=await save(),video=changed.clips[0];assert.equal(video.duration,2);assert.equal(video.speed,2);assert.equal(video.in,1);assert.equal(video.start,2);
    await page.keyboard.press('Control+z');assert.equal((await save()).clips[0].duration,4);await page.keyboard.press('Control+Shift+z');assert.equal((await save()).clips[0].duration,2);
    await stretch('video','left',.5);video=(await save()).clips[0];assert.equal(video.start,2.5);assert.equal(video.duration,1.5);assert.ok(Math.abs(video.speed*video.duration-4)<1e-9);
    assert.ok(await page.getByLabel('再生速度',{exact:true}).inputValue());await page.keyboard.press('Control+z');await stretch('video','right',1,true);assert.equal((await save()).clips[0].duration,2);checks.push('both edges preserve IN/OUT, fractional speed is visible, one Undo/Redo and Escape work');
    const lost=await page.locator('.timeline-clip.video .trim-handle.right').boundingBox();await page.mouse.move(lost.x+2,lost.y+10);await page.mouse.down();await page.mouse.move(lost.x+zoom,lost.y+10,{steps:5});await page.locator('.timeline-clip.video .trim-handle.right').evaluate(el=>el.dispatchEvent(new PointerEvent('lostpointercapture',{bubbles:true})));await page.mouse.up();assert.equal((await save()).clips[0].duration,2);await page.keyboard.press('Control+z');assert.equal((await save()).clips[0].duration,4);await page.keyboard.press('Control+Shift+z');checks.push('lost pointer capture cancels a rate gesture and releases keyboard commands');
    await stretch('audio','right',-2);let final=await save();assert.equal(final.clips[1].speed,2);assert.equal(final.clips[1].duration,2);assert.equal(final.clips[1].in,1);
    const track=p.tracks.find(t=>t.id===a.trackId);await page.getByRole('button',{name:track.name+' ロック',exact:true}).click();assert.equal(await page.locator('.timeline-clip.audio').evaluate(el=>getComputedStyle(el).cursor),'not-allowed');const locked=await page.locator('.timeline-clip.audio').boundingBox();await page.mouse.move(locked.x+20,locked.y+20);await page.mouse.down();await page.mouse.move(locked.x+100,locked.y+20);await page.mouse.up();assert.equal((await save()).clips[1].duration,2);await page.getByRole('button',{name:track.name+' ロック解除',exact:true}).click();checks.push('audio rate uses the same source interval and locked tracks refuse gestures');
    await page.keyboard.press('Home');await page.keyboard.press('r');assert.match(await page.locator('.ruler-label .timecode').textContent(),/00:00:00:01/);await save();await page.keyboard.press('Control+o');await page.waitForFunction(()=>document.querySelector('button[aria-label="元に戻す (Ctrl+Z)"]').disabled);await page.screenshot({path:path.join(results,'rate-stretch-editor.png')});
    const output=path.join(results,'レート調整.mp4');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},output);await page.getByRole('button',{name:'書き出し',exact:true}).click();await page.getByLabel('品質',{exact:true}).selectOption('draft');await page.getByLabel('書き出し方式',{exact:true}).selectOption('cpu');await page.getByRole('button',{name:'保存先を選んで書き出す',exact:true}).click();await page.getByText('書き出しが完了しました',{exact:true}).waitFor({timeout:120000});assert.ok(Math.abs(Number((await probe(output)).format.duration)-4)<.06);
    const pixels=[];for(const t of [2.25,3.75]){const buf=await run(ffmpeg,['-v','error','-ss',String(t),'-i',output,'-frames:v','1','-vf','scale=1:1','-pix_fmt','rgb24','-f','rawvideo','pipe:1']);pixels.push([...buf]);}assert.ok(pixels[0][2]>200&&pixels[1][0]>200);
    const pcm=await run(ffmpeg,['-v','error','-ss','2.25','-i',output,'-t','1','-vn','-ac','1','-ar','48000','-f','f32le','pipe:1']);let energy=0;for(let i=0;i<pcm.length;i+=4)energy+=pcm.readFloatLE(i)**2;const rms=Math.sqrt(energy/(pcm.length/4));assert.ok(rms>.04);checks.push('R still advances one frame, rate survives reload, MP4 retains both source endpoints and audible soundtrack');
    await page.keyboard.press('Escape');await page.getByRole('button',{name:'選択ツール (V)',exact:true}).click();await page.locator('.timeline-scroll').evaluate(el=>{el.scrollTop=0;});const alternate=p.tracks.find(t=>t.kind==='video'&&t.id!==v.trackId),body=await page.locator('.timeline-clip.video').boundingBox(),lane=await page.locator('[data-track-id="'+alternate.id+'"]').boundingBox();assert.equal(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('.timeline-clip')?.getAttribute('data-clip-id'),{x:body.x+body.width/2,y:body.y+body.height/2}),v.id);assert.equal(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.closest('[data-track-id]')?.getAttribute('data-track-id'),{x:body.x+body.width/2,y:lane.y+lane.height/2}),alternate.id);await page.mouse.move(body.x+body.width/2,body.y+body.height/2);await page.mouse.down();await page.mouse.move(body.x+body.width/2,lane.y+lane.height/2,{steps:8});await page.mouse.up();const reassigned=await save();assert.equal(reassigned.clips[0].trackId,alternate.id);assert.equal(reassigned.clips[0].start,2);checks.push('pure vertical movement keeps pointer capture when a clip changes track');
    assert.deepEqual(errors,[]);await fs.writeFile(path.join(results,'rate-verification.json'),JSON.stringify({passed:true,packaged:!!executablePath,checks,pixels,rms,consoleErrors:errors},null,2));console.log('Video and audio rate stretching verified.');
  }catch(error){await page.screenshot({path:path.join(results,'rate-failure.png')}).catch(()=>{});throw error;}finally{await app.close();}
}verify().catch(error=>{console.error(error);process.exitCode=1;});
