const {_electron:electron}=require('playwright');const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');const {createHash}=require('node:crypto');
const {ffmpeg,run,probe}=require('../electron/media.cjs');const root=path.join(__dirname,'..');
const verifyBgmVolume=require('./verify-bgm-volume.cjs');
async function verify(){
  const results=path.join(root,'test-results');await fs.mkdir(results,{recursive:true});await fs.mkdir(path.join(root,'.local'),{recursive:true});
  const profile=await fs.mkdtemp(path.join(root,'.local','bgm-profile-')),portable=await fs.mkdtemp(path.join(root,'.local','bgm-portable-')),folder=path.join(portable,'bgm');await fs.mkdir(folder);
  const song=path.join(folder,'短い チャイム.mp3'),long=path.join(folder,'長い 音楽75秒.wav');
  await run(ffmpeg,['-v','error','-y','-f','lavfi','-i','sine=frequency=660:sample_rate=48000:duration=3','-c:a','libmp3lame',song]);
  await run(ffmpeg,['-v','error','-y','-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=75',long]);await fs.writeFile(path.join(folder,'壊れた音楽.mp3'),'not audio');
  const hash=async file=>createHash('sha256').update(await fs.readFile(file)).digest('hex'),beforeHash=await hash(song);
  const env={...process.env,LUMA_TEST_DATA:profile,PORTABLE_EXECUTABLE_DIR:portable};delete env.ELECTRON_RUN_AS_NODE;const executablePath=process.env.LUMA_VERIFY_EXE;
  const app=await electron.launch({executablePath,args:executablePath?[]:[root],env,timeout:60000}),page=await app.firstWindow(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const file=path.join(results,'BGM検証.luma');
  const save=async()=>{const before=(await fs.stat(file).catch(()=>null))?.mtimeMs;await page.getByRole('button',{name:'プロジェクトを保存 (Ctrl+S)',exact:true}).click();const deadline=Date.now()+10000;while((await fs.stat(file).catch(()=>null))?.mtimeMs===before){assert.ok(Date.now()<deadline,'save completed');await new Promise(r=>setTimeout(r,25));}return JSON.parse(await fs.readFile(file,'utf8'));};
  try{
    await page.locator('.media-card').first().waitFor({timeout:60000});await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);
    const demo=await save(),baseVideo=demo.clips.find(c=>c.kind==='video'),fixture={...demo,id:'bgm-sequence',name:'BGMの実機検証',width:320,height:180,markers:[],transitions:[],clips:[{...baseVideo,id:'bgm-video',start:0,in:0,duration:6,volume:0,fadeIn:0,fadeOut:0,linkId:undefined}]};
    await fs.writeFile(file,JSON.stringify(fixture));await page.keyboard.press('Control+o');await page.getByRole('button',{name:fixture.name,exact:true}).waitFor();
    await page.getByRole('tab',{name:'BGM',exact:true}).click();await page.locator('.bgm-track').first().waitFor({timeout:60000});assert.equal(await page.locator('.bgm-track').count(),2);assert.equal(await page.getByLabel('追加するBGMの音量',{exact:true}).inputValue(),'10');assert.equal(await page.getByLabel('BGMの追加する長さ',{exact:true}).inputValue(),'fit');assert.equal(await page.locator('.bgm-errors').count(),1);checks.push('portable bgm folder is found automatically with Japanese names, durations and a corrupt-file report');
    await page.getByLabel('BGMを検索',{exact:true}).fill('75秒');assert.equal(await page.locator('.bgm-track').count(),1);assert.ok((await page.locator('.bgm-track time').innerText()).includes('01:15'));await page.getByLabel('BGMを検索',{exact:true}).fill('');checks.push('search finds long music without a one-minute duration cutoff');
    const chooseShort=()=>page.getByRole('button',{name:'短い チャイム.mp3 00:03',exact:true}).click();
    await chooseShort();await page.getByRole('button',{name:'選択したBGMを試聴',exact:true}).click();await page.waitForFunction(()=>{const a=document.querySelector('.bgm-player');return a&&!a.paused&&a.currentTime>.1;});assert.equal(await page.locator('.bgm-player').evaluate(a=>a.volume),.1);await page.keyboard.press('Escape');assert.ok(await page.locator('.bgm-player').evaluate(a=>a.paused));checks.push('audition plays decoded audio at the insertion volume and Escape stops it');
    await page.getByRole('button',{name:'選択したBGMを試聴',exact:true}).click();await page.getByRole('button',{name:'試聴を停止',exact:true}).waitFor();await page.getByRole('button',{name:'長い 音楽75秒.wav 01:15',exact:true}).click();assert.ok(await page.locator('.bgm-player').evaluate(a=>a.paused));
    await chooseShort();await page.getByRole('button',{name:'選択したBGMを試聴',exact:true}).click();await page.getByRole('button',{name:'試聴を停止',exact:true}).waitFor();await page.getByRole('tab',{name:'メディア',exact:true}).click();assert.equal(await page.locator('.bgm-player').count(),0);checks.push('changing songs and leaving the BGM panel stop audition');
    await page.getByRole('tab',{name:'BGM',exact:true}).click();await page.locator('.bgm-track').first().waitFor();await chooseShort();await page.keyboard.press('Home');const zoom=Number(await page.getByRole('slider',{name:'タイムラインのズーム',exact:true}).inputValue());await page.locator('.timeline-ruler').click({position:{x:zoom,y:24}});
    await page.getByRole('button',{name:'BGMをタイムラインに追加',exact:true}).click();await page.getByText(/BGMを追加しました/).waitFor();let saved=await save(),added=saved.clips.filter(c=>c.kind==='audio');assert.equal(added.length,2);assert.equal(added[0].start,1);assert.equal(added.at(-1).start+added.at(-1).duration,6);assert.ok(added.every(c=>c.volume===.1));assert.equal(Math.max(...saved.clips.map(c=>c.start+c.duration)),6);checks.push('insertion starts at the playhead and repeats only to the existing video end');
    const addedAsset=added[0].assetId;await page.keyboard.press('Control+z');saved=await save();assert.equal(saved.clips.length,1);assert.ok(!saved.assets.some(a=>a.id===addedAsset));await page.keyboard.press('Control+Shift+z');saved=await save();assert.equal(saved.clips.filter(c=>c.kind==='audio').length,2);checks.push('one Undo removes the imported asset and all repeats, and Redo restores them');
    await page.locator('.timeline-clip[data-clip-id="'+added[0].id+'"]').focus();await page.keyboard.press('Enter');await page.locator('#prop-volume').fill('30');await page.getByRole('tab',{name:'BGM',exact:true}).click();saved=await save();assert.equal(saved.clips.find(c=>c.id===added[0].id).volume,.3);checks.push('inserted music uses the normal clip volume controls');
    await page.keyboard.press('Control+o');await page.waitForFunction(()=>document.querySelector('button[aria-label="元に戻す (Ctrl+Z)"]')?.disabled);saved=await save();assert.equal(saved.clips.filter(c=>c.kind==='audio').length,2);checks.push('BGM source paths and repeated placements survive project save and reload');
    const parked=song+'.missing';await fs.rename(song,parked);await page.keyboard.press('Control+o');await page.waitForFunction(()=>document.querySelectorAll('.timeline-clip.offline').length===2);await fs.rename(parked,song);
    await page.getByRole('tab',{name:'BGM',exact:true}).click();await page.locator('.bgm-track').first().waitFor();await chooseShort();await page.getByLabel('追加するBGMの音量',{exact:true}).focus();await page.keyboard.press('Home');assert.equal(await page.getByLabel('追加するBGMの音量',{exact:true}).inputValue(),'0');
    await page.getByRole('button',{name:'BGMをタイムラインに追加',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.timeline-clip.audio').length===4 && document.querySelectorAll('.timeline-clip.offline').length===0);saved=await save();assert.equal(saved.assets.filter(a=>a.id===addedAsset).length,1);assert.ok(saved.clips.filter(c=>c.kind==='audio').every(c=>c.assetId===addedAsset));checks.push('restoring the original song and reinserting it repairs existing offline clips without duplicating the asset; new clips are muted to verify the restored originals in export');
    const output=path.join(results,'BGM付き動画.mp4');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},output);await page.getByRole('button',{name:'書き出し',exact:true}).click();await page.getByLabel('書き出し方式',{exact:true}).selectOption('cpu');await page.getByLabel('品質',{exact:true}).selectOption('high');await page.getByRole('button',{name:'保存先を選んで書き出す',exact:true}).click();await page.getByText('書き出しが完了しました',{exact:true}).waitFor({timeout:120000});assert.ok(Math.abs(Number((await probe(output)).format.duration)-6)<.06);
    const pcm=await run(ffmpeg,['-v','error','-i',output,'-vn','-ac','1','-ar','48000','-f','f32le','pipe:1']);const rms=(from,to)=>{let sum=0,n=0;for(let i=Math.floor(from*48000);i<Math.floor(to*48000)&&i*4<pcm.length;i++){sum+=pcm.readFloatLE(i*4)**2;n++;}return Math.sqrt(sum/n);};assert.ok(rms(.2,.6)<.0001);assert.ok(rms(2,2.5)>.015);assert.ok(rms(4.5,4.9)>.004);assert.ok(rms(5.85,5.95)<rms(4.5,4.9)*.5);checks.push('real MP4 stays six seconds, is silent before insertion, plays both repetitions and fades at the end');await page.keyboard.press('Escape');
    await fs.copyFile(song,path.join(folder,'追加の曲.mp3'));await page.getByRole('button',{name:'BGM一覧を更新',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.bgm-track').length===3);checks.push('refresh discovers a newly added song');
    const empty=path.join(portable,'別の空フォルダ');await fs.mkdir(empty);await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},empty);await page.getByRole('button',{name:'フォルダを選択',exact:true}).click();await page.getByText('音楽がありません。MP3などが入ったフォルダを選択してください。',{exact:true}).waitFor();assert.equal(JSON.parse(await fs.readFile(path.join(profile,'bgm-library.json'),'utf8')).folder,empty);checks.push('folder selection persists and an empty folder presents a useful message');
    await app.evaluate(({dialog},folder)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folder]});},folder);await page.getByRole('button',{name:'フォルダを選択',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.bgm-track').length===3);
    await page.screenshot({path:path.join(results,'bgm-library.png')});assert.equal(await hash(song),beforeHash);assert.deepEqual(errors,[]);checks.push('original MP3 bytes are unchanged and no renderer exceptions occurred');
    const volumePresets=await verifyBgmVolume({app,page,save,projectFile:file,results,checks});assert.equal(await hash(song),beforeHash);assert.deepEqual(errors,[]);
    await fs.writeFile(path.join(results,'bgm-verification.json'),JSON.stringify({passed:true,packaged:!!executablePath,checks,outputDuration:6,outputRms:{before:rms(.2,.6),first:rms(2,2.5),repeat:rms(4.5,4.9),fade:rms(5.85,5.95)},volumePresets,consoleErrors:errors},null,2));console.log(`BGM library verified: ${checks.length} checks.`);
  }catch(e){await page.screenshot({path:path.join(results,'bgm-failure.png')}).catch(()=>{});throw e;}finally{await app.close();}
}
verify().catch(e=>{console.error(e);process.exitCode=1;});
