import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url)), out=path.join(root,'dist');
await rm(out,{recursive:true,force:true});await mkdir(out,{recursive:true});await cp(path.join(root,'assets'),path.join(out,'assets'),{recursive:true});
const repo='https://github.com/altimix/LumaStudio', release=repo+'/releases/tag/v1.0.0', download=repo+'/releases/download/v1.0.0/';
const logo='<a class="logo" href="/" aria-label="Luma Studio ホーム"><img src="/assets/favicon.svg" width="31" height="31" alt=""><span>Luma<span>Studio</span></span></a>';
const nav=`<a class="skip" href="#main">本文へ移動</a><header class="site-header"><div class="nav-wrap">${logo}<nav aria-label="メインナビゲーション"><a href="/#features">機能</a><a href="/manual/">マニュアル</a><a href="/support/">開発を支援</a><a class="nav-download" href="/#download">ダウンロード <span aria-hidden="true">↗</span></a></nav></div></header>`;
const footer=`<footer class="site-footer"><div>${logo}<p>映像づくりを、もっと身近に。</p><small>© 2026 株式会社Altimix</small></div><div><a href="/manual/">マニュアル</a><a href="/getting-started/">初めての動画編集</a><a href="/support/">開発に参加・支援</a></div><div><a href="${repo}">GitHub ↗</a><a href="${repo}/issues">不具合・機能の提案 ↗</a><a href="/about/">このソフトとサイトについて</a></div><p class="footer-note">アプリ：GPL-3.0-only · 初期BGM：CC BY 4.0</p></footer>`;
function page(title,description,body,url='/'){return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} | Luma Studio</title><meta name="description" content="${description}"><link rel="canonical" href="https://lumastudio.altimix.jp${url}"><meta property="og:title" content="${title} | Luma Studio"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:url" content="https://lumastudio.altimix.jp${url}"><meta property="og:image" content="https://lumastudio.altimix.jp/assets/editor.png"><meta name="theme-color" content="#213d31"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"></head><body>${nav}<main id="main">${body}</main>${footer}</body></html>`;}
async function save(name,html){const dest=path.join(out,name);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,html);}
const home=`<section class="hero wrap"><div class="eyebrow"><span class="status-dot"></span> FREE & OPEN SOURCE <span class="version">v1.0.0</span></div><div class="hero-grid"><h1>右手はマウス。<br>左手で、編集<span class="dot">。</span></h1><div class="hero-copy"><p>よく使う編集ショートカットを、キーボードの左手側に。<br>右手で素材や再生位置を選び、左手でカット・トリミング・ズーム。マウスとキーを組み合わせて、編集を進められます。音量も、タイムライン上で直接調整できます。</p><p class="muted">Windows・Macで使える、日本語の動画編集ソフト。<br>研究の記録も、授業の教材も、日々の発信も。</p><div class="actions"><a class="button" href="#download">無料でダウンロード <span aria-hidden="true">↓</span></a><a class="text-link" href="/getting-started/">使い方を見る <span aria-hidden="true">↗</span></a></div></div></div><figure class="editor-shot"><div class="shot-bar"><span>● ● ●</span><span>LUMA STUDIO — EDITING WORKSPACE</span><span>01 / 03</span></div><img src="/assets/editor.png" width="1600" height="968" alt="Luma Studioの編集画面。映像プレビュー、素材ライブラリ、複数トラックのタイムラインを並べて編集できます。" fetchpriority="high"><figcaption>編集画面の例。初回起動時は素材・タイムラインが空の状態です。<span>映像：Sintel / Blender Foundation · <a href="/about/#credits">クレジット</a></span></figcaption></figure></section>
<section class="principles wrap" aria-label="ソフトの特徴"><span>Windows & Mac</span><span>左手にまとまる編集キー</span><span>タイムラインで音量編集</span><span>ソースコード公開</span></section>
<section class="section wrap left-hand" aria-labelledby="left-hand-title"><div><p class="eyebrow">LEFT HAND SHORTCUTS</p><h2 id="left-hand-title">よく使う操作が、<br>左手の近くに。</h2><p>カットするたび、ズームするたびに、画面のボタンを探す。<br>その操作を、左手側のキーで進められます。</p><p><strong>Z</strong>で全トラックに編集点を追加。<strong>Q / W</strong>で前後を詰め、<strong>A / S</strong>でタイムラインを拡大・縮小。<strong>E / R</strong>で1フレームずつ位置を調整できます。</p><a class="text-link" href="/manual/#commands">キーボード図で操作を確かめる ↗</a></div><div class="left-keys" aria-label="左手側の主なショートカット。位置はQWERTY配列の概略です。"><div><span><kbd>Q</kbd><small>前を詰める</small></span><span><kbd>W</kbd><small>後ろを詰める</small></span><span><kbd>E</kbd><small>1コマ戻る</small></span><span><kbd>R</kbd><small>1コマ進む</small></span></div><div><span><kbd>A</kbd><small>拡大</small></span><span><kbd>S</kbd><small>縮小</small></span></div><div><span><kbd>Z</kbd><small>全トラック<br>カット</small></span></div><p>Q / Wは再生ヘッドを基準にリップルトリミング。詳しい対象・条件はマニュアルで確認できます。</p></div></section>
<section class="section wrap" id="features"><div class="section-head"><div><p class="eyebrow">MAKE YOUR STORY</p><h2>一本を仕上げるための、<br>基本をひとつに。</h2></div><p>素材の読み込みから、最後の書き出しまで。<br>映像・文字・音を、同じ画面で整えられます。</p></div><div class="feature-grid"><article><div class="feature-art tracks" aria-hidden="true"><i></i><i></i><i></i><b></b></div><span class="feature-number">01 / EDIT</span><h3>切って、つなぐ。</h3><p>複数トラックで動画・画像・音声を組み合わせる。分割やトリミング、Undo / Redoで、試しながら編集できます。</p></article><article><div class="feature-art title-art" aria-hidden="true"><span>伝わる、ことば。</span><i></i></div><span class="feature-number">02 / TEXT</span><h3>言葉を添える。</h3><p>日本語テロップの位置・大きさ・見た目を調整。タイトルや説明を、映像に合わせて配置できます。</p></article><article><div class="feature-art wave-art" aria-hidden="true">${Array.from({length:29},(_,i)=>`<i style="height:${18+((i*19)%57)}px"></i>`).join('')}</div><span class="feature-number">03 / SOUND</span><h3>音量も、タイムラインで。</h3><p>音量ラインに点を追加し、上下にドラッグして調整。話している間はBGMを下げ、場面の切り替わりで上げる。映像と波形を見ながら、区間ごとに音量を整えられます。</p><a class="text-link" href="/manual/#audio">音量ラインの使い方を見る ↗</a></article></div></section>
<section class="wrap audio-showcase" aria-labelledby="audio-shot-title"><p class="eyebrow">TIMELINE AUDIO EDITING</p><h2 id="audio-shot-title">音の強弱を、点と線で。</h2><p>波形と重ねて見える音量ライン。点を上下に動かすと、その位置の音量を調整できます。</p><figure><a href="/assets/audio-timeline.png" aria-label="音量編集の画面全体を見る"><img src="/assets/audio-timeline.png" width="1600" height="968" loading="lazy" alt="実際のLuma Studioの音声タイムライン。メイン音声に複数の黄色い音量ポイントが並び、青い選択ポイントと区間ごとの音量ラインが見えます。下段にはミュージックの波形が表示されています。"></a><figcaption>実際の編集画面のタイムライン部分。黄色の点が音量ポイント、青い点が選択中のポイントです。<a href="/assets/audio-timeline.png">画面全体を見る ↗</a></figcaption></figure><p class="muted">操作例には検証用の合成音声を使用しています。初回起動時のタイムラインは空です。</p><a class="text-link" href="/manual/#audio">音量ラインの使い方を見る ↗</a></section>
<section class="learn-band"><div class="wrap learn-inner"><div><p class="eyebrow">FIRST STEPS</p><h2>初めての一本を、<br>一緒に作ろう。</h2><p>素材を読み込む、並べる、短くする、書き出す。<br>基本の流れを、5つのステップで紹介します。</p><a class="button light" href="/getting-started/">初めての動画編集 <span aria-hidden="true">↗</span></a></div><div class="learn-links"><a href="/manual/#media"><span>01</span><strong>素材を読み込む</strong><span>↗</span></a><a href="/manual/#commands"><span>02</span><strong>ショートカットを調べる</strong><span>↗</span></a><a href="/manual/#export"><span>03</span><strong>動画を書き出す</strong><span>↗</span></a><a href="/manual/#trouble"><span>04</span><strong>困ったときは</strong><span>↗</span></a></div></div></section>
<section class="section wrap" id="download"><div class="section-head"><div><p class="eyebrow">START CREATING</p><h2>あなたのPCで、始める。</h2></div><p>公開安定版 <strong>1.0.0</strong><br><a href="${release}">リリース内容を確認 ↗</a></p></div><div class="download-grid"><article class="download-card"><span class="platform-symbol" aria-hidden="true">⊞</span><h3>Windows</h3><p>64ビット（x64）・ポータブル版</p><a class="button" href="${download}Luma-Studio-1.0.0-Windows.exe">Windows版をダウンロード ↓</a><small>EXE · 約123 MB</small><a href="${download}README-Windows.txt">Windowsでの起動方法 ↗</a></article><article class="download-card"><span class="platform-symbol" aria-hidden="true">⌘</span><h3>Mac</h3><p>Apple Silicon（M1以降）</p><a class="button" href="${download}Luma-Studio-1.0.0-macOS-arm64.zip">Mac版をダウンロード ↓</a><small>ZIP · 約161 MB · Intel Mac向けではありません</small><a href="${download}README-Mac.txt">Macでの起動方法 ↗</a></article></div><div class="download-note"><p>配布アプリは未署名です。起動時にOSの確認が出る場合は、各OSの起動方法をご覧ください。更新は新しい配布版を取得して入れ替えます。</p><p>1.0.0のMP4書き出しはCPU方式です。GPU書き出し・アプリ内の更新確認は開発中です。<a href="${repo}/issues">開発状況 ↗</a></p><a href="${download}SHA256SUMS.txt">ダウンロードファイルのSHA256 ↗</a></div></section>
<section class="community wrap"><div><p class="eyebrow">BUILT IN THE OPEN</p><h2>使う人と、育てていく。</h2><p>不具合の報告、使い方の提案、コードやマニュアルの改善。<br>あなたの気づきが、次のLuma Studioにつながります。</p></div><a class="button outline" href="/support/">開発に参加・支援する ↗</a></section>`;
await save('index.html',page('左手のショートカットで編集できる無料動画編集ソフト','カット・トリミング・ズームのショートカットが左手側にまとまった、日本語の動画編集ソフト。Windows・Mac対応。ダウンロードと操作マニュアルはこちら。',home));
const steps=[['素材を読み込む','右上の「読み込み」から、自分の動画・画像・音声を選びます。素材はPC上に保存したまま使うので、編集後も元ファイルを残してください。','media'],['タイムラインに並べる','素材を選び、「選択素材をタイムラインに追加」を押します。映像や音声のクリップをドラッグして、順番や開始位置を調整します。','start'],['必要なところを残す','クリップの端をドラッグして長さを調整します。再生ヘッドを置いて分割し、不要な部分を削除します。失敗してもCtrl＋Z（Macは⌘＋Z）で戻せます。','commands'],['文字とBGMを添える','テキストを追加して、映像に合わせて位置や大きさを調整します。BGMタブでは初期BGM5曲を試聴・追加できます。音量を下げ、声の聞こえ方も確認しましょう。','audio'],['保存して、MP4に書き出す','まずプロジェクトを保存します。右上の「書き出し」でサイズ・品質を選び、MP4を保存します。プロジェクトファイルと完成動画は別のファイルです。','export']];
await save('getting-started/index.html',page('初めての動画編集','素材を読み込むところからMP4の書き出しまで、Luma Studioの基本操作を5ステップで紹介します。',`<div class="article wrap"><p class="eyebrow">GETTING STARTED / v1.0.0</p><h1>初めての動画編集</h1><p class="lead">まずは短い動画を一本。<br>この5つの操作から始めましょう。</p><a class="text-link" href="/#download">まだインストールしていない方はこちら ↗</a><div class="steps">${steps.map(([title,desc,id],i)=>`<section><span class="step-number">0${i+1}</span><div><h2>${title}</h2><p>${desc}</p><a href="/manual/#${id}">マニュアルで詳しく見る ↗</a></div></section>`).join('')}</div><aside class="callout"><h2>よく使うキー</h2><p><kbd>Space</kbd> 再生・停止　<kbd>J</kbd> 逆再生　<kbd>K</kbd> 停止　<kbd>L</kbd> 再生・早送り</p><a href="/manual/#commands">検索できるショートカット一覧へ ↗</a></aside></div>`,'/getting-started/'));
await save('support/index.html',page('開発に参加・支援する','不具合報告、機能提案、コードやマニュアルの改善でLuma Studioの開発に参加できます。',`<div class="article wrap"><p class="eyebrow">SUPPORT THE PROJECT</p><h1>一緒に、使いやすく。</h1><p class="lead">Luma Studioは、ソースコードを公開して開発しています。<br>プログラミング以外の参加も歓迎します。</p><aside class="callout donation"><p class="eyebrow">SUPPORT DEVELOPMENT</p><h2>開発へのご支援をお考えの方へ</h2><p>開発・保守、動作確認の継続を支える任意のご支援については、株式会社Altimixへお問い合わせください。「Luma Studioの開発支援」とお書き添えいただくとスムーズです。</p><a class="button" href="https://altimix.co.jp/contact/">支援について問い合わせる ↗</a></aside><div class="support-list"><section><span>01</span><div><h2>気づいたことを教える</h2><p>不具合や「こうできたら便利」をGitHubのIssueへ。OS、アプリのバージョン、操作手順があると調査に役立ちます。個人情報や非公開の素材は投稿しないでください。</p><a class="button outline" href="${repo}/issues/new">Issueを作成する ↗</a></div></section><section><span>02</span><div><h2>コード・マニュアルを改善する</h2><p>小さな修正も歓迎します。関連Issueと開発手順を確認し、変更内容と検証結果を添えてPRを送ってください。</p><a class="button outline" href="${repo}/blob/main/CONTRIBUTING.md">開発への参加方法 ↗</a></div></section><section><span>03</span><div><h2>使い方を広める</h2><p>授業や研究、制作で役立った使い方を共有したり、この公式サイトを紹介したりすることも、開発の支援になります。</p><a class="text-link" href="/manual/">操作マニュアルへ ↗</a></div></section></div><aside class="callout"><p>ご支援の有無にかかわらず、アプリのすべての機能をご利用いただけます。</p></aside></div>`,'/support/'));
await save('about/index.html',page('このソフトとサイトについて','Luma Studioの公開元、ライセンス、利用素材とプライバシーについて。',`<div class="article wrap prose"><p class="eyebrow">ABOUT LUMA STUDIO</p><h1>このソフトとサイトについて</h1><h2>公開・開発</h2><p>Luma Studioは<a href="https://altimix.co.jp/">株式会社Altimix</a>が開発・公開する、Windows・macOS向けの日本語動画編集ソフトです。ソースコード、変更履歴、不具合報告は<a href="${repo}">GitHubリポジトリ</a>で公開しています。</p><h2>ライセンス</h2><p>アプリは<a href="${repo}/blob/main/LICENSE">GPL-3.0-only</a>、初期BGM001〜005は<a href="${repo}/blob/main/BGM-LICENSE.txt">CC BY 4.0</a>で提供しています。利用・再配布・改変時はそれぞれのライセンスをご確認ください。第三者のソフトウェアについては<a href="${repo}/blob/main/THIRD_PARTY_NOTICES.md">第三者ライセンス一覧</a>をご覧ください。</p><h2 id="credits">画面例に使用している映像</h2><p>Sintel — © copyright Blender Foundation | <a href="https://www.sintel.org">www.sintel.org</a>。<a href="https://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a>。画面例では抜粋・サイズ変更・再エンコードした映像にテロップを加えています。Blender Foundationによる推奨を示すものではありません。画面例の映像は初期プロジェクトには配置されません。</p><h2>プライバシーと外部サービス</h2><p>このサイトはCloudflareで配信しています。独自のアクセス解析タグ、広告、会員登録、問い合わせフォームは設置していません。配信・セキュリティのためのアクセス情報はCloudflareで処理される場合があります。<a href="https://www.cloudflare.com/privacypolicy/">Cloudflareのプライバシーポリシー</a>をご覧ください。</p><p>アプリのダウンロードやIssueへの投稿ではGitHubに移動します。アプリの基本的な編集・MP4出力はローカルで処理しますが、任意のAI機能には別途API設定が必要で、利用時は対象の音声や指示などを外部サービスへ送信します。詳しくは<a href="/manual/#youtube">マニュアル</a>をご確認ください。</p><h2>運営会社・お問い合わせ</h2><p>株式会社Altimix（Altimix Inc.）<br>〒107-0062 東京都港区南青山2-2-15 ウィン青山</p><p><a href="https://altimix.co.jp/company/">会社概要</a> · <a href="https://altimix.co.jp/contact/">会社へのお問い合わせ</a></p><h2>不具合報告</h2><p>公開できる不具合・改善提案は<a href="${repo}/issues">GitHub Issues</a>へお願いします。認証情報、個人情報、非公開素材を含めないでください。</p></div>`,'/about/'));
let manual=await readFile(path.join(root,'../README.html'),'utf8');
manual=manual.replace('</head>','<link rel="canonical" href="https://lumastudio.altimix.jp/manual/"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><style>.site-return{display:block;padding:12px 24px;background:#e6eddf;color:#213d31;font:14px/1.5 sans-serif;text-decoration:none}@media print{.site-return{display:none}}</style></head>').replace('<body>','<body><a class="site-return" href="/">← Luma Studio 公式サイトに戻る</a>');
// Preserve the offline guide and all its searchable commands; add only online navigation and favicon permissions.
manual=manual.replace("default-src 'none';", "default-src 'none'; img-src 'self';");
const keyboardCss = await readFile(path.join(root, 'assets/keyboard.css'), 'utf8');
const keyboardJs = await readFile(path.join(root, 'assets/keyboard.js'), 'utf8');
manual = manual.replace('</head>', `<style>${keyboardCss}</style></head>`)
  .replace('<h2>全コマンド・ショートカット一覧</h2>', '<h2>全コマンド・ショートカット一覧</h2><div id="keyboard-guide" hidden></div>')
  .replace('</body>', `<script>${keyboardJs}</script></body>`);
await save('manual/index.html',manual);
await save('404.html',page('ページが見つかりません','Luma Studio公式サイトのホームやマニュアルからお探しください。','<div class="article wrap"><p class="eyebrow">404 / NOT FOUND</p><h1>ページが見つかりません。</h1><p>アドレスが変わったか、ページが存在しないようです。</p><a class="button" href="/">ホームに戻る</a> <a href="/manual/">マニュアルを見る</a></div>','/404'));
await save('robots.txt','User-agent: *\nAllow: /\nSitemap: https://lumastudio.altimix.jp/sitemap.xml\n');
await save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/','/manual/','/getting-started/','/support/','/about/'].map(p=>`<url><loc>https://lumastudio.altimix.jp${p}</loc></url>`).join('')+'</urlset>');
await save('_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: DENY\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'\n`);
console.log('Built official site and manual:',out);
