export const origin = 'https://lumastudio.altimix.jp';
export const developerTitle = '開発者 安藤昇｜学校で動画編集を学ぶために';
export const developerDescription = 'スタディサプリ情報Ⅰ・プログラミング講師、青山学院中等部・青山学院大学非常勤講師の安藤昇が開発。広告なしの国産動画編集ソフトLuma Studioに込めた思いと、学校での利用について紹介します。';

const credentials = `<ul class="developer-credentials"><li>スタディサプリ 情報Ⅰ・プログラミング講師</li><li>青山学院中等部・青山学院大学 非常勤講師</li></ul>`;
const portrait = `<img class="developer-portrait" src="/assets/noboru-ando.png" width="1080" height="1080" loading="lazy" decoding="async" alt="Luma Studio開発者・安藤昇の写真">`;
const message = `<blockquote class="developer-message"><p>学校で、生徒が動画編集の基本を学べるソフトを作りたい。その思いから、Luma Studioを開発しました。広告を表示せず、素材を並べる、切る、文字や音を加える、一本の動画に仕上げるという学びに集中できることを大切にしています。</p><p>もちろん、社会人の方にも使っていただけます。仕事の説明動画や日々の記録、YouTubeの動画づくりにも。基本機能を中心に、必要な編集をしっかりこなせる、シンプルで高機能な動画編集ソフトを目指しています。</p><footer>安藤 昇 <span>／ Luma Studio 開発者</span></footer></blockquote>`;

export const homeTrust = `<section class="section wrap developer-section" id="developer" aria-labelledby="developer-title"><div class="developer-intro"><div><p class="eyebrow">DEVELOPED IN JAPAN</p><h2 id="developer-title">教える人がつくった、<br>動画編集の学びの道具。</h2><p class="developer-summary">Luma Studioは、情報教育に携わる安藤昇が開発した国産の無料動画編集ソフトです。学校での最初の一本から、仕事やYouTubeの動画づくりまで。</p><a class="text-link" href="/developer/">開発者の思いと、学校での利用について ↗</a></div><figure class="developer-profile">${portrait}<figcaption><strong>安藤 昇</strong><span>Noboru Ando</span>${credentials}</figcaption></figure></div>${message}<div class="trust-points"><article><h3>広告なし・会員登録なし</h3><p>アプリ内に広告を表示しません。アカウントを作らず、無料で基本の動画編集を始められます。</p></article><article><h3>基本の編集はPCの中で</h3><p>動画のカット、文字や音の追加、MP4への書き出しはローカルで処理します。任意のAI機能の利用時には外部送信とAPI利用料が発生します。</p></article><article><h3>開発者とソースを公開</h3><p>株式会社Altimixが公開し、ソースコードと変更履歴をGitHubで確認できます。使う前に、出所と仕組みを確かめられます。</p></article></div></section>`;

export const developerBody = `<div class="article wrap developer-page"><p class="eyebrow">THE DEVELOPER</p><h1>学校で学ぶ一本から、<br>自分らしく伝える一本へ。</h1><div class="developer-page-profile">${portrait}<div><h2>開発者 安藤 昇</h2><p class="roman-name">Noboru Ando</p>${credentials}<p>情報教育に携わる安藤昇が企画・開発し、株式会社Altimixが公開する、日本発の動画編集ソフトです。</p></div></div><h2>開発者からのメッセージ</h2>${message}<section class="prose"><h2>基本に集中できる、国産の動画編集ソフト</h2><p>Luma Studioは、動画編集の基本を学ぶために、カット・トリミング・テロップ・音量調整・MP4出力をひとつの画面にまとめました。複数トラックやショートカットを使いながら、映像・文字・音を組み合わせて表現する力を育てられます。</p><p>アプリは広告なし、会員登録なしで利用できます。学校の授業や生徒の作品づくりはもちろん、社会人の仕事や趣味、YouTube向けの制作にもお使いいただけます。</p><p>「国産」は、日本の開発者が企画・開発していることを表しています。アプリにはElectronやFFmpegなど国内外のオープンソースソフトウェアを使用し、<a href="https://github.com/altimix/LumaStudio/blob/main/THIRD_PARTY_NOTICES.md">第三者ライセンス</a>を公開しています。</p><h2 id="school">学校で安心して使うために</h2><p>教員や管理者が導入を判断できるように、利用条件とデータの扱いを公開しています。所属先の端末管理・個人情報のルールに沿ってご利用ください。</p><dl class="school-details"><dt>広告・登録・費用</dt><dd>アプリ内広告と会員登録はありません。基本編集とMP4出力は無料です。任意のAI機能にはOpenAI APIキーが必要で、API利用料が別途発生します。</dd><dt>素材と外部通信</dt><dd>基本的な編集・書き出しはPC内で処理します。AI機能を実行すると、対象の音声や指示などをOpenAIへ送信します。生徒の声・氏名・非公開素材を扱う場合は、学校のルールと必要な同意を確認してください。更新情報の確認ではGitHubに接続します。</dd><dt>配布元と起動時の確認</dt><dd>この公式サイトから案内するGitHub Releasesで入手してください。Windows版は未署名、Mac版はad-hoc署名付きで、Developer ID署名・Apple公証は未対応です。OSの確認画面が出る場合があります。管理端末では管理者に確認のうえ、<a href="/#download">各OSの起動手順とSHA256</a>をご利用ください。</dd><dt>作品とライセンス</dt><dd>生徒の写真・声・映像の公開範囲と、利用する素材の権利を確認してください。アプリはGPL-3.0-only、初期BGMはCC BY 4.0です。詳しくは<a href="/about/">ライセンスと公開元の情報</a>をご覧ください。</dd></dl><p class="affiliation-note">肩書きは開発者の活動を紹介するものです。本ソフトは株式会社Altimixが独自に開発・公開しており、記載した学校・サービスによる公式製品や推奨を示すものではありません。</p><h2>使い方を学ぶ</h2><p><a href="/getting-started/">初めての動画編集</a>では、読み込みから書き出しまでを5ステップで紹介しています。YouTubeの<a href="https://www.youtube.com/watch?v=jWi7rb4ne-M">安藤昇による使い方の解説動画</a>や、<a href="/manual/">日本語の操作マニュアル</a>もご利用ください。</p><p><a class="button" href="/#download">無料でダウンロード ↓</a></p></section></div>`;

export function searchMetadata(title, description, route, version) {
  const person = {'@type':'Person','@id':`${origin}/developer/#person`,name:'安藤昇',alternateName:'Noboru Ando',url:`${origin}/developer/`,image:`${origin}/assets/noboru-ando.png`,description:'スタディサプリ 情報Ⅰ・プログラミング講師。青山学院中等部・青山学院大学 非常勤講師。Luma Studio開発者。'};
  const organization = {'@type':'Organization','@id':`${origin}/#organization`,name:'株式会社Altimix',url:'https://altimix.co.jp/'};
  const website = {'@type':'WebSite','@id':`${origin}/#website`,url:`${origin}/`,name:'Luma Studio',alternateName:['LumaStudio','ルマスタジオ'],inLanguage:'ja',publisher:{'@id':organization['@id']}};
  const graph = [organization,website,{'@type':route==='/developer/'?'AboutPage':'WebPage','@id':`${origin}${route}#webpage`,url:`${origin}${route}`,name:title,description,inLanguage:'ja',isPartOf:{'@id':website['@id']},...(route==='/developer/'?{about:{'@id':person['@id']}}:{})}];
  if(route==='/'||route==='/developer/') graph.push(person);
  if(route==='/') graph.push({'@type':'SoftwareApplication','@id':`${origin}/#software`,name:'Luma Studio',url:`${origin}/`,applicationCategory:'MultimediaApplication',operatingSystem:['Windows (x64)','macOS (Apple Silicon)'],softwareVersion:version,inLanguage:'ja',isAccessibleForFree:true,description:'広告なし・会員登録なし。安藤昇が開発した国産の無料動画編集ソフト。学校での学習から仕事やYouTubeの動画制作まで。任意のAI機能は別途API利用料が必要です。',creator:{'@id':person['@id']},publisher:{'@id':organization['@id']},license:'https://www.gnu.org/licenses/gpl-3.0.html',downloadUrl:`${origin}/#download`,offers:{'@type':'Offer',price:'0',priceCurrency:'JPY'}});
  const json = JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
  return `<meta name="robots" content="${route==='/404'?'noindex, follow':'index, follow, max-image-preview:large'}"><meta property="og:site_name" content="Luma Studio"><meta property="og:locale" content="ja_JP"><script type="application/ld+json">${json}</script>`;
}
